<?php
?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<title>Käuferportal Fragenbogen</title>
	<?php echo $this->render('js.phtml')?>
</head>
<body>
<h1>Käuferportal Fragenbogen</h1>
<p>Bitte selektieren Sie einen Produkt:</p>
<p>
<form action="<?php echo $this->baseUrl?>/questionaire">
	<select name="uuid">
		<?php
			foreach ($this->options as $uuid => $label)
				echo "<option value='$uuid'>$label</option>";
		?>
	</select>
	<input type="submit" value='Zum Fragenbogen'></input>
</form>
</p>
<!-- 
 -->
</body>
</html>
