<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<title>Käuferprortal Fragenbogen</title>
	<link rel='stylesheet' href='<?php echo $this->baseUrl ?>/public/styles/kp.css' />
	<?php echo $this->render('js.phtml')?>
</head>
<body>
<h1>Käuferprortal Fragenbogen</h1>
<form action='<?php echo $this->baseUrl?>/questionaire/page' method='post'>
	<table class='page'>
	<?php 
		foreach ($this->page['questions'] as $i => $question) {
			$question['number'] = $i+ 1;
			$this->question = $question;
			echo $this->render('question.phtml');
		}
		
	?>
	</table>
	<div style='display:none'>
		<input name='uuid' value='<?php echo $this->uuid?>'>
		<input name='page' value='<?php echo $this->page['number']?>'>
		<input name='answers' value='<?php echo Zend_Json::encode($this->answers)?>'>
	</div>
	<input type="submit" value='Weiter'></input>
</form>
</body>
</html>
